Repository Deva-Coders/inventario-frontend, pull requests merged in 2024-08, with the labels that each got.

#27 Feat/link component
  src/components/CustomLink/CustomLink.css
  src/components/CustomLink/CustomLink.tsx
  src/index.css
Labels: enhancement

#28 Feat/modal
  src/components/Popup/Popup.css
  src/components/Popup/Popup.tsx
  src/components/RegisterForm/RegisterForm.tsx
  src/hooks/usePopup.ts
Labels: enhancement

#30 Fix/input form component
  src/components/ErrorMessage/ErrorMessage.css
  src/components/InputForm/InputForm.css
  src/components/InputForm/InputForm.tsx
  src/components/InputPasswordForm/InputPasswordForm.css
  src/components/InputPasswordForm/InputPasswordForm.tsx
  src/components/RegisterForm/RegisterForm.tsx
  src/index.css
Labels: bug, enhancement, Refactor

#31 Fix/recover pass btn
  src/pages/RecoverPasswordPage.tsx
Labels: bug

#32 Feat/use fetch
  src/hooks/useFetch.ts
Labels: enhancement

#34 Feat/password input with requirements component
  src/components/Checkbox/Checkbox.css
  src/components/Checkbox/Checkbox.tsx
  src/components/Icon/Icon.tsx
  src/components/InputPasswordForm/InputPasswordForm.tsx
  src/components/PasswordInputWithRequirements/PasswordInputWithRequirements.css
  src/components/PasswordInputWithRequirements/PasswordInputWithRequirements.tsx
  src/components/Requirements/Requirements.css
  src/components/Requirements/Requirements.tsx
  src/helpers/helpMessageError.ts
  src/helpers/helpValidatePassword.ts
  src/index.css
  src/types/ErrorMessage.ts
  src/types/Requirements.ts
Labels: enhancement

#35 Feat/register page
  src/components/InputForm/InputForm.tsx
  src/components/InputPhoneForm/InputPhoneForm.css
  src/components/InputPhoneForm/InputPhoneForm.tsx
  src/components/RegisterForm/RegisterForm.tsx
  src/components/SecurityQuestion/SecurityQuestion.css
  src/components/SecurityQuestion/SecurityQuestion.tsx
Labels: bug, enhancement

#39 fix: add title and HeroLogo
  src/pages/RegisterUserPage.css
  src/pages/RegisterUserPage.tsx
Labels: enhancement

#40 Merge pull request #37 from Deva-Coders/feat/add-logo
  src/pages/QuestionPage.css
  src/pages/QuestionPage.tsx
Labels: bug, Refactor

#33 Feat/new password
  src/main.tsx
  src/pages/NewPasswordPage.css
  src/pages/NewPasswordPage.tsx
Labels: enhancement

#41 Feat/login page
  src/App.tsx
  src/components/Button/Button.css
  src/components/Button/Button.tsx
  src/components/ButtonBackIcon/ButtonBackIcon.css
  src/components/CustomLink/CustomLink.css
  src/components/ErrorMessage/ErrorMessage.css
  src/components/ErrorMessage/ErrorMessage.tsx
  src/components/Icon/Icon.css
  src/components/Icon/Icon.tsx
  src/components/ProtectedRoute/ProtectedRoute.tsx
  src/components/RegisterForm/RegisterForm.css
  src/components/RegisterForm/RegisterForm.tsx
  src/context/AuthContext.tsx
  src/hooks/usePopup.ts
  src/index.css
  src/main.tsx
  src/pages/Login/Login.css
  src/pages/Login/Login.tsx
  src/pages/Login/components/formLogin/formLogin.css
  src/pages/Login/components/formLogin/formLogin.tsx
  src/pages/LoginPage.tsx
Labels: enhancement, Refactor

#42 fix: position back button arrow
  src/components/ButtonBackIcon/ButtonBackIcon.css
Labels: bug

#45 refactor: change styles of Links in HomePage
  src/pages/Home/HomePage.css
Labels: Refactor

#36 Feat/product add page
  src/components/ProductForm/ProductsAdd.module.css
  src/components/ProductForm/ProductsAdd.tsx
  src/interfaces/index.tsx
  src/pages/ProductPage.tsx
Labels: enhancement

#47 Feat/notfound page
  src/App.tsx
  src/pages/Error/ErrorPage.module.css
  src/pages/Error/ErrorPage.tsx
  src/pages/index.ts
Labels: enhancement

#48 Feat/change favicon, name
  index.html
Labels: enhancement

#49 Feat/add terms and conditions checkbox
  src/components/Checkbox/Checkbox.css
  src/components/Checkbox/Checkbox.tsx
  src/components/Icon/Icon.css
  src/components/InputForm/InputForm.tsx
  src/components/InputPasswordForm/InputPasswordForm.tsx
  src/components/InputPhoneForm/InputPhoneForm.css
  src/components/InputPhoneForm/InputPhoneForm.tsx
  src/components/PasswordInputWithRequirements/PasswordInputWithRequirements.css
  src/components/SecurityQuestion/SecurityQuestion.css
  src/components/SecurityQuestion/SecurityQuestion.tsx
  src/helpers/helpMessageError.ts
  src/pages/Login/components/formLogin/formLogin.tsx
  src/pages/Register/components/RegisterForm/RegisterForm.css
  src/pages/Register/components/RegisterForm/RegisterForm.tsx
  src/types/ErrorMessage.ts
Labels: Refactor

#53 docs: data interaction flow diagrams
  docs/LoginDataInteractionFlowDiagram.png
  docs/RegisterDataInteractionFlowDiagram.png
  docs/ResetPasswordDataInteractionFlowDiagram.png
Labels: documentation
